// Code generated by ent, DO NOT EDIT.

package fitnesstestitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Godx1an/gp_ent/pkg/ent_work/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldDeletedAt, v))
}

// Item applies equality check predicate on the "item" field. It's identical to ItemEQ.
func Item(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldItem, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldDeletedAt, v))
}

// ItemEQ applies the EQ predicate on the "item" field.
func ItemEQ(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEQ(FieldItem, v))
}

// ItemNEQ applies the NEQ predicate on the "item" field.
func ItemNEQ(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNEQ(FieldItem, v))
}

// ItemIn applies the In predicate on the "item" field.
func ItemIn(vs ...string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldIn(FieldItem, vs...))
}

// ItemNotIn applies the NotIn predicate on the "item" field.
func ItemNotIn(vs ...string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldNotIn(FieldItem, vs...))
}

// ItemGT applies the GT predicate on the "item" field.
func ItemGT(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGT(FieldItem, v))
}

// ItemGTE applies the GTE predicate on the "item" field.
func ItemGTE(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldGTE(FieldItem, v))
}

// ItemLT applies the LT predicate on the "item" field.
func ItemLT(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLT(FieldItem, v))
}

// ItemLTE applies the LTE predicate on the "item" field.
func ItemLTE(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldLTE(FieldItem, v))
}

// ItemContains applies the Contains predicate on the "item" field.
func ItemContains(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldContains(FieldItem, v))
}

// ItemHasPrefix applies the HasPrefix predicate on the "item" field.
func ItemHasPrefix(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldHasPrefix(FieldItem, v))
}

// ItemHasSuffix applies the HasSuffix predicate on the "item" field.
func ItemHasSuffix(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldHasSuffix(FieldItem, v))
}

// ItemEqualFold applies the EqualFold predicate on the "item" field.
func ItemEqualFold(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldEqualFold(FieldItem, v))
}

// ItemContainsFold applies the ContainsFold predicate on the "item" field.
func ItemContainsFold(v string) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.FieldContainsFold(FieldItem, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FitnessTestItem) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FitnessTestItem) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FitnessTestItem) predicate.FitnessTestItem {
	return predicate.FitnessTestItem(sql.NotPredicates(p))
}
