// Code generated by ent, DO NOT EDIT.

package ent_work

import (
	"time"

	"github.com/Godx1an/gp_ent/pkg/ent_work/admin"
	"github.com/Godx1an/gp_ent/pkg/ent_work/fitnesstestitem"
	"github.com/Godx1an/gp_ent/pkg/ent_work/schema"
	"github.com/Godx1an/gp_ent/pkg/ent_work/school"
	"github.com/Godx1an/gp_ent/pkg/ent_work/schoolfitnesstestitem"
	"github.com/Godx1an/gp_ent/pkg/ent_work/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminMixin := schema.Admin{}.Mixin()
	adminMixinFields0 := adminMixin[0].Fields()
	_ = adminMixinFields0
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescCreatedBy is the schema descriptor for created_by field.
	adminDescCreatedBy := adminMixinFields0[1].Descriptor()
	// admin.DefaultCreatedBy holds the default value on creation for the created_by field.
	admin.DefaultCreatedBy = adminDescCreatedBy.Default.(int64)
	// adminDescUpdatedBy is the schema descriptor for updated_by field.
	adminDescUpdatedBy := adminMixinFields0[2].Descriptor()
	// admin.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	admin.DefaultUpdatedBy = adminDescUpdatedBy.Default.(int64)
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminMixinFields0[3].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updated_at field.
	adminDescUpdatedAt := adminMixinFields0[4].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminDescDeletedAt is the schema descriptor for deleted_at field.
	adminDescDeletedAt := adminMixinFields0[5].Descriptor()
	// admin.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	admin.DefaultDeletedAt = adminDescDeletedAt.Default.(time.Time)
	// adminDescPhone is the schema descriptor for phone field.
	adminDescPhone := adminFields[0].Descriptor()
	// admin.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	admin.PhoneValidator = func() func(string) error {
		validators := adminDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminDescSchool is the schema descriptor for school field.
	adminDescSchool := adminFields[3].Descriptor()
	// admin.DefaultSchool holds the default value on creation for the school field.
	admin.DefaultSchool = adminDescSchool.Default.(string)
	// adminDescID is the schema descriptor for id field.
	adminDescID := adminMixinFields0[0].Descriptor()
	// admin.DefaultID holds the default value on creation for the id field.
	admin.DefaultID = adminDescID.Default.(func() int64)
	fitnesstestitemMixin := schema.FitnessTestItem{}.Mixin()
	fitnesstestitemMixinFields0 := fitnesstestitemMixin[0].Fields()
	_ = fitnesstestitemMixinFields0
	fitnesstestitemFields := schema.FitnessTestItem{}.Fields()
	_ = fitnesstestitemFields
	// fitnesstestitemDescCreatedBy is the schema descriptor for created_by field.
	fitnesstestitemDescCreatedBy := fitnesstestitemMixinFields0[1].Descriptor()
	// fitnesstestitem.DefaultCreatedBy holds the default value on creation for the created_by field.
	fitnesstestitem.DefaultCreatedBy = fitnesstestitemDescCreatedBy.Default.(int64)
	// fitnesstestitemDescUpdatedBy is the schema descriptor for updated_by field.
	fitnesstestitemDescUpdatedBy := fitnesstestitemMixinFields0[2].Descriptor()
	// fitnesstestitem.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	fitnesstestitem.DefaultUpdatedBy = fitnesstestitemDescUpdatedBy.Default.(int64)
	// fitnesstestitemDescCreatedAt is the schema descriptor for created_at field.
	fitnesstestitemDescCreatedAt := fitnesstestitemMixinFields0[3].Descriptor()
	// fitnesstestitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	fitnesstestitem.DefaultCreatedAt = fitnesstestitemDescCreatedAt.Default.(func() time.Time)
	// fitnesstestitemDescUpdatedAt is the schema descriptor for updated_at field.
	fitnesstestitemDescUpdatedAt := fitnesstestitemMixinFields0[4].Descriptor()
	// fitnesstestitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fitnesstestitem.DefaultUpdatedAt = fitnesstestitemDescUpdatedAt.Default.(func() time.Time)
	// fitnesstestitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fitnesstestitem.UpdateDefaultUpdatedAt = fitnesstestitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fitnesstestitemDescDeletedAt is the schema descriptor for deleted_at field.
	fitnesstestitemDescDeletedAt := fitnesstestitemMixinFields0[5].Descriptor()
	// fitnesstestitem.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	fitnesstestitem.DefaultDeletedAt = fitnesstestitemDescDeletedAt.Default.(time.Time)
	// fitnesstestitemDescID is the schema descriptor for id field.
	fitnesstestitemDescID := fitnesstestitemMixinFields0[0].Descriptor()
	// fitnesstestitem.DefaultID holds the default value on creation for the id field.
	fitnesstestitem.DefaultID = fitnesstestitemDescID.Default.(func() int64)
	schoolMixin := schema.School{}.Mixin()
	schoolMixinFields0 := schoolMixin[0].Fields()
	_ = schoolMixinFields0
	schoolFields := schema.School{}.Fields()
	_ = schoolFields
	// schoolDescCreatedBy is the schema descriptor for created_by field.
	schoolDescCreatedBy := schoolMixinFields0[1].Descriptor()
	// school.DefaultCreatedBy holds the default value on creation for the created_by field.
	school.DefaultCreatedBy = schoolDescCreatedBy.Default.(int64)
	// schoolDescUpdatedBy is the schema descriptor for updated_by field.
	schoolDescUpdatedBy := schoolMixinFields0[2].Descriptor()
	// school.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	school.DefaultUpdatedBy = schoolDescUpdatedBy.Default.(int64)
	// schoolDescCreatedAt is the schema descriptor for created_at field.
	schoolDescCreatedAt := schoolMixinFields0[3].Descriptor()
	// school.DefaultCreatedAt holds the default value on creation for the created_at field.
	school.DefaultCreatedAt = schoolDescCreatedAt.Default.(func() time.Time)
	// schoolDescUpdatedAt is the schema descriptor for updated_at field.
	schoolDescUpdatedAt := schoolMixinFields0[4].Descriptor()
	// school.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	school.DefaultUpdatedAt = schoolDescUpdatedAt.Default.(func() time.Time)
	// school.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	school.UpdateDefaultUpdatedAt = schoolDescUpdatedAt.UpdateDefault.(func() time.Time)
	// schoolDescDeletedAt is the schema descriptor for deleted_at field.
	schoolDescDeletedAt := schoolMixinFields0[5].Descriptor()
	// school.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	school.DefaultDeletedAt = schoolDescDeletedAt.Default.(time.Time)
	// schoolDescID is the schema descriptor for id field.
	schoolDescID := schoolMixinFields0[0].Descriptor()
	// school.DefaultID holds the default value on creation for the id field.
	school.DefaultID = schoolDescID.Default.(func() int64)
	schoolfitnesstestitemMixin := schema.SchoolFitnessTestItem{}.Mixin()
	schoolfitnesstestitemMixinFields0 := schoolfitnesstestitemMixin[0].Fields()
	_ = schoolfitnesstestitemMixinFields0
	schoolfitnesstestitemFields := schema.SchoolFitnessTestItem{}.Fields()
	_ = schoolfitnesstestitemFields
	// schoolfitnesstestitemDescCreatedBy is the schema descriptor for created_by field.
	schoolfitnesstestitemDescCreatedBy := schoolfitnesstestitemMixinFields0[1].Descriptor()
	// schoolfitnesstestitem.DefaultCreatedBy holds the default value on creation for the created_by field.
	schoolfitnesstestitem.DefaultCreatedBy = schoolfitnesstestitemDescCreatedBy.Default.(int64)
	// schoolfitnesstestitemDescUpdatedBy is the schema descriptor for updated_by field.
	schoolfitnesstestitemDescUpdatedBy := schoolfitnesstestitemMixinFields0[2].Descriptor()
	// schoolfitnesstestitem.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	schoolfitnesstestitem.DefaultUpdatedBy = schoolfitnesstestitemDescUpdatedBy.Default.(int64)
	// schoolfitnesstestitemDescCreatedAt is the schema descriptor for created_at field.
	schoolfitnesstestitemDescCreatedAt := schoolfitnesstestitemMixinFields0[3].Descriptor()
	// schoolfitnesstestitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	schoolfitnesstestitem.DefaultCreatedAt = schoolfitnesstestitemDescCreatedAt.Default.(func() time.Time)
	// schoolfitnesstestitemDescUpdatedAt is the schema descriptor for updated_at field.
	schoolfitnesstestitemDescUpdatedAt := schoolfitnesstestitemMixinFields0[4].Descriptor()
	// schoolfitnesstestitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schoolfitnesstestitem.DefaultUpdatedAt = schoolfitnesstestitemDescUpdatedAt.Default.(func() time.Time)
	// schoolfitnesstestitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schoolfitnesstestitem.UpdateDefaultUpdatedAt = schoolfitnesstestitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// schoolfitnesstestitemDescDeletedAt is the schema descriptor for deleted_at field.
	schoolfitnesstestitemDescDeletedAt := schoolfitnesstestitemMixinFields0[5].Descriptor()
	// schoolfitnesstestitem.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	schoolfitnesstestitem.DefaultDeletedAt = schoolfitnesstestitemDescDeletedAt.Default.(time.Time)
	// schoolfitnesstestitemDescMaxParticipants is the schema descriptor for max_participants field.
	schoolfitnesstestitemDescMaxParticipants := schoolfitnesstestitemFields[0].Descriptor()
	// schoolfitnesstestitem.DefaultMaxParticipants holds the default value on creation for the max_participants field.
	schoolfitnesstestitem.DefaultMaxParticipants = schoolfitnesstestitemDescMaxParticipants.Default.(int)
	// schoolfitnesstestitemDescAvgTimePerPerson is the schema descriptor for avg_time_per_person field.
	schoolfitnesstestitemDescAvgTimePerPerson := schoolfitnesstestitemFields[1].Descriptor()
	// schoolfitnesstestitem.DefaultAvgTimePerPerson holds the default value on creation for the avg_time_per_person field.
	schoolfitnesstestitem.DefaultAvgTimePerPerson = schoolfitnesstestitemDescAvgTimePerPerson.Default.(int)
	// schoolfitnesstestitemDescSchoolID is the schema descriptor for school_id field.
	schoolfitnesstestitemDescSchoolID := schoolfitnesstestitemFields[2].Descriptor()
	// schoolfitnesstestitem.DefaultSchoolID holds the default value on creation for the school_id field.
	schoolfitnesstestitem.DefaultSchoolID = schoolfitnesstestitemDescSchoolID.Default.(int64)
	// schoolfitnesstestitemDescItemID is the schema descriptor for item_id field.
	schoolfitnesstestitemDescItemID := schoolfitnesstestitemFields[3].Descriptor()
	// schoolfitnesstestitem.DefaultItemID holds the default value on creation for the item_id field.
	schoolfitnesstestitem.DefaultItemID = schoolfitnesstestitemDescItemID.Default.(int64)
	// schoolfitnesstestitemDescID is the schema descriptor for id field.
	schoolfitnesstestitemDescID := schoolfitnesstestitemMixinFields0[0].Descriptor()
	// schoolfitnesstestitem.DefaultID holds the default value on creation for the id field.
	schoolfitnesstestitem.DefaultID = schoolfitnesstestitemDescID.Default.(func() int64)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedBy is the schema descriptor for created_by field.
	userDescCreatedBy := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedBy holds the default value on creation for the created_by field.
	user.DefaultCreatedBy = userDescCreatedBy.Default.(int64)
	// userDescUpdatedBy is the schema descriptor for updated_by field.
	userDescUpdatedBy := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	user.DefaultUpdatedBy = userDescUpdatedBy.Default.(int64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescDeletedAt is the schema descriptor for deleted_at field.
	userDescDeletedAt := userMixinFields0[5].Descriptor()
	// user.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	user.DefaultDeletedAt = userDescDeletedAt.Default.(time.Time)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[0].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = func() func(string) error {
		validators := userDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescSchool is the schema descriptor for school field.
	userDescSchool := userFields[3].Descriptor()
	// user.DefaultSchool holds the default value on creation for the school field.
	user.DefaultSchool = userDescSchool.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() int64)
}
