// Code generated by ent, DO NOT EDIT.

package ent_work

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godx1an/gp_ent/pkg/ent_work/student"
)

// StudentCreate is the builder for creating a Student entity.
type StudentCreate struct {
	config
	mutation *StudentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "created_by" field.
func (sc *StudentCreate) SetCreatedBy(i int64) *StudentCreate {
	sc.mutation.SetCreatedBy(i)
	return sc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sc *StudentCreate) SetNillableCreatedBy(i *int64) *StudentCreate {
	if i != nil {
		sc.SetCreatedBy(*i)
	}
	return sc
}

// SetUpdatedBy sets the "updated_by" field.
func (sc *StudentCreate) SetUpdatedBy(i int64) *StudentCreate {
	sc.mutation.SetUpdatedBy(i)
	return sc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sc *StudentCreate) SetNillableUpdatedBy(i *int64) *StudentCreate {
	if i != nil {
		sc.SetUpdatedBy(*i)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *StudentCreate) SetCreatedAt(t time.Time) *StudentCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *StudentCreate) SetNillableCreatedAt(t *time.Time) *StudentCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *StudentCreate) SetUpdatedAt(t time.Time) *StudentCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *StudentCreate) SetNillableUpdatedAt(t *time.Time) *StudentCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *StudentCreate) SetDeletedAt(t time.Time) *StudentCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *StudentCreate) SetNillableDeletedAt(t *time.Time) *StudentCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetName sets the "name" field.
func (sc *StudentCreate) SetName(s string) *StudentCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sc *StudentCreate) SetNillableName(s *string) *StudentCreate {
	if s != nil {
		sc.SetName(*s)
	}
	return sc
}

// SetNickName sets the "nick_name" field.
func (sc *StudentCreate) SetNickName(s string) *StudentCreate {
	sc.mutation.SetNickName(s)
	return sc
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (sc *StudentCreate) SetNillableNickName(s *string) *StudentCreate {
	if s != nil {
		sc.SetNickName(*s)
	}
	return sc
}

// SetJpgURL sets the "jpg_url" field.
func (sc *StudentCreate) SetJpgURL(s string) *StudentCreate {
	sc.mutation.SetJpgURL(s)
	return sc
}

// SetNillableJpgURL sets the "jpg_url" field if the given value is not nil.
func (sc *StudentCreate) SetNillableJpgURL(s *string) *StudentCreate {
	if s != nil {
		sc.SetJpgURL(*s)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *StudentCreate) SetID(i int64) *StudentCreate {
	sc.mutation.SetID(i)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *StudentCreate) SetNillableID(i *int64) *StudentCreate {
	if i != nil {
		sc.SetID(*i)
	}
	return sc
}

// Mutation returns the StudentMutation object of the builder.
func (sc *StudentCreate) Mutation() *StudentMutation {
	return sc.mutation
}

// Save creates the Student in the database.
func (sc *StudentCreate) Save(ctx context.Context) (*Student, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StudentCreate) SaveX(ctx context.Context) *Student {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StudentCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StudentCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StudentCreate) defaults() {
	if _, ok := sc.mutation.CreatedBy(); !ok {
		v := student.DefaultCreatedBy
		sc.mutation.SetCreatedBy(v)
	}
	if _, ok := sc.mutation.UpdatedBy(); !ok {
		v := student.DefaultUpdatedBy
		sc.mutation.SetUpdatedBy(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := student.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := student.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.DeletedAt(); !ok {
		v := student.DefaultDeletedAt
		sc.mutation.SetDeletedAt(v)
	}
	if _, ok := sc.mutation.Name(); !ok {
		v := student.DefaultName
		sc.mutation.SetName(v)
	}
	if _, ok := sc.mutation.NickName(); !ok {
		v := student.DefaultNickName
		sc.mutation.SetNickName(v)
	}
	if _, ok := sc.mutation.JpgURL(); !ok {
		v := student.DefaultJpgURL
		sc.mutation.SetJpgURL(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := student.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StudentCreate) check() error {
	if _, ok := sc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent_work: missing required field "Student.created_by"`)}
	}
	if _, ok := sc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent_work: missing required field "Student.updated_by"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent_work: missing required field "Student.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent_work: missing required field "Student.updated_at"`)}
	}
	if _, ok := sc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent_work: missing required field "Student.deleted_at"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent_work: missing required field "Student.name"`)}
	}
	if _, ok := sc.mutation.NickName(); !ok {
		return &ValidationError{Name: "nick_name", err: errors.New(`ent_work: missing required field "Student.nick_name"`)}
	}
	if _, ok := sc.mutation.JpgURL(); !ok {
		return &ValidationError{Name: "jpg_url", err: errors.New(`ent_work: missing required field "Student.jpg_url"`)}
	}
	return nil
}

func (sc *StudentCreate) sqlSave(ctx context.Context) (*Student, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StudentCreate) createSpec() (*Student, *sqlgraph.CreateSpec) {
	var (
		_node = &Student{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(student.Table, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = sc.conflict
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.CreatedBy(); ok {
		_spec.SetField(student.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := sc.mutation.UpdatedBy(); ok {
		_spec.SetField(student.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(student.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(student.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(student.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(student.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.NickName(); ok {
		_spec.SetField(student.FieldNickName, field.TypeString, value)
		_node.NickName = value
	}
	if value, ok := sc.mutation.JpgURL(); ok {
		_spec.SetField(student.FieldJpgURL, field.TypeString, value)
		_node.JpgURL = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Student.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudentUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (sc *StudentCreate) OnConflict(opts ...sql.ConflictOption) *StudentUpsertOne {
	sc.conflict = opts
	return &StudentUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Student.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sc *StudentCreate) OnConflictColumns(columns ...string) *StudentUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &StudentUpsertOne{
		create: sc,
	}
}

type (
	// StudentUpsertOne is the builder for "upsert"-ing
	//  one Student node.
	StudentUpsertOne struct {
		create *StudentCreate
	}

	// StudentUpsert is the "OnConflict" setter.
	StudentUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedBy sets the "created_by" field.
func (u *StudentUpsert) SetCreatedBy(v int64) *StudentUpsert {
	u.Set(student.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *StudentUpsert) UpdateCreatedBy() *StudentUpsert {
	u.SetExcluded(student.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *StudentUpsert) AddCreatedBy(v int64) *StudentUpsert {
	u.Add(student.FieldCreatedBy, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *StudentUpsert) SetUpdatedBy(v int64) *StudentUpsert {
	u.Set(student.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *StudentUpsert) UpdateUpdatedBy() *StudentUpsert {
	u.SetExcluded(student.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *StudentUpsert) AddUpdatedBy(v int64) *StudentUpsert {
	u.Add(student.FieldUpdatedBy, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudentUpsert) SetUpdatedAt(v time.Time) *StudentUpsert {
	u.Set(student.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudentUpsert) UpdateUpdatedAt() *StudentUpsert {
	u.SetExcluded(student.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *StudentUpsert) SetDeletedAt(v time.Time) *StudentUpsert {
	u.Set(student.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *StudentUpsert) UpdateDeletedAt() *StudentUpsert {
	u.SetExcluded(student.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *StudentUpsert) SetName(v string) *StudentUpsert {
	u.Set(student.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StudentUpsert) UpdateName() *StudentUpsert {
	u.SetExcluded(student.FieldName)
	return u
}

// SetNickName sets the "nick_name" field.
func (u *StudentUpsert) SetNickName(v string) *StudentUpsert {
	u.Set(student.FieldNickName, v)
	return u
}

// UpdateNickName sets the "nick_name" field to the value that was provided on create.
func (u *StudentUpsert) UpdateNickName() *StudentUpsert {
	u.SetExcluded(student.FieldNickName)
	return u
}

// SetJpgURL sets the "jpg_url" field.
func (u *StudentUpsert) SetJpgURL(v string) *StudentUpsert {
	u.Set(student.FieldJpgURL, v)
	return u
}

// UpdateJpgURL sets the "jpg_url" field to the value that was provided on create.
func (u *StudentUpsert) UpdateJpgURL() *StudentUpsert {
	u.SetExcluded(student.FieldJpgURL)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Student.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(student.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StudentUpsertOne) UpdateNewValues() *StudentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(student.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(student.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Student.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StudentUpsertOne) Ignore() *StudentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudentUpsertOne) DoNothing() *StudentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudentCreate.OnConflict
// documentation for more info.
func (u *StudentUpsertOne) Update(set func(*StudentUpsert)) *StudentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudentUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *StudentUpsertOne) SetCreatedBy(v int64) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *StudentUpsertOne) AddCreatedBy(v int64) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateCreatedBy() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *StudentUpsertOne) SetUpdatedBy(v int64) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *StudentUpsertOne) AddUpdatedBy(v int64) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateUpdatedBy() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudentUpsertOne) SetUpdatedAt(v time.Time) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateUpdatedAt() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *StudentUpsertOne) SetDeletedAt(v time.Time) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateDeletedAt() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *StudentUpsertOne) SetName(v string) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateName() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateName()
	})
}

// SetNickName sets the "nick_name" field.
func (u *StudentUpsertOne) SetNickName(v string) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetNickName(v)
	})
}

// UpdateNickName sets the "nick_name" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateNickName() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateNickName()
	})
}

// SetJpgURL sets the "jpg_url" field.
func (u *StudentUpsertOne) SetJpgURL(v string) *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.SetJpgURL(v)
	})
}

// UpdateJpgURL sets the "jpg_url" field to the value that was provided on create.
func (u *StudentUpsertOne) UpdateJpgURL() *StudentUpsertOne {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateJpgURL()
	})
}

// Exec executes the query.
func (u *StudentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent_work: missing options for StudentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StudentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StudentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StudentCreateBulk is the builder for creating many Student entities in bulk.
type StudentCreateBulk struct {
	config
	err      error
	builders []*StudentCreate
	conflict []sql.ConflictOption
}

// Save creates the Student entities in the database.
func (scb *StudentCreateBulk) Save(ctx context.Context) ([]*Student, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Student, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StudentCreateBulk) SaveX(ctx context.Context) []*Student {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StudentCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StudentCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Student.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudentUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (scb *StudentCreateBulk) OnConflict(opts ...sql.ConflictOption) *StudentUpsertBulk {
	scb.conflict = opts
	return &StudentUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Student.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scb *StudentCreateBulk) OnConflictColumns(columns ...string) *StudentUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &StudentUpsertBulk{
		create: scb,
	}
}

// StudentUpsertBulk is the builder for "upsert"-ing
// a bulk of Student nodes.
type StudentUpsertBulk struct {
	create *StudentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Student.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(student.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StudentUpsertBulk) UpdateNewValues() *StudentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(student.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(student.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Student.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StudentUpsertBulk) Ignore() *StudentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudentUpsertBulk) DoNothing() *StudentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudentCreateBulk.OnConflict
// documentation for more info.
func (u *StudentUpsertBulk) Update(set func(*StudentUpsert)) *StudentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudentUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *StudentUpsertBulk) SetCreatedBy(v int64) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *StudentUpsertBulk) AddCreatedBy(v int64) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateCreatedBy() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *StudentUpsertBulk) SetUpdatedBy(v int64) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *StudentUpsertBulk) AddUpdatedBy(v int64) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateUpdatedBy() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudentUpsertBulk) SetUpdatedAt(v time.Time) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateUpdatedAt() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *StudentUpsertBulk) SetDeletedAt(v time.Time) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateDeletedAt() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *StudentUpsertBulk) SetName(v string) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateName() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateName()
	})
}

// SetNickName sets the "nick_name" field.
func (u *StudentUpsertBulk) SetNickName(v string) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetNickName(v)
	})
}

// UpdateNickName sets the "nick_name" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateNickName() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateNickName()
	})
}

// SetJpgURL sets the "jpg_url" field.
func (u *StudentUpsertBulk) SetJpgURL(v string) *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.SetJpgURL(v)
	})
}

// UpdateJpgURL sets the "jpg_url" field to the value that was provided on create.
func (u *StudentUpsertBulk) UpdateJpgURL() *StudentUpsertBulk {
	return u.Update(func(s *StudentUpsert) {
		s.UpdateJpgURL()
	})
}

// Exec executes the query.
func (u *StudentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent_work: OnConflict was set for builder %d. Set it on the StudentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent_work: missing options for StudentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
